version: "3.5"

services:
  clickhouse:
    container_name: suite_clickhouse
    network_mode: host
    image: "yandex/clickhouse-server:latest"

  nginx:
    image: nginx:1.17
    container_name: suite_nginx
    network_mode: host
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"